### ISSUE TITLE
Create Modal

### ISSUE THREAD

**Issue by sjyoung428** [pknu-wap/wap-ui#31]
# 작업 리스트

- [x] Modal  만들기
- [x] Modal Header 만들기
- [x] Modal Body 만들기
- [x] Modal Footer 만들기
- [x] Overlay 만들기
- [x] 스크롤 방지
- [x] close 기능

## 참고사항
![모달참고](https://user-images.githubusercontent.com/77968955/194278621-2d6b6166-ce22-4f87-943f-338633787ae7.png)

## 예상 소요 시간
중간 발표 전까지

**Comment by alstn113** [comment]
branch만 계속 올리셔도 돼요.
그게 다른 사람이 merge 전 부터 코드를 주기적으로 확인하기 편할 거 같아요.

**Comment by sjyoung428** [comment]
![image](https://user-images.githubusercontent.com/77968955/198042411-1cc57f5b-30f3-482a-b4dc-f0eb039e2bf3.png)
이런식으로 모달 사용하게 될듯?
