### ISSUE TITLE
Create Toast Component

### ISSUE THREAD

**Issue by sjyoung428** [pknu-wap/wap-ui#54]
# 작업 리스트

- [x] position
- [x] animation
- [x] timeout
- [x] message type

**Comment by sjyoung428** [comment]
어렵다

**Comment by sjyoung428** [comment]
[asdf.webm](https://user-images.githubusercontent.com/77968955/204142905-a7c56bdc-14aa-4334-bd3f-9918142b8867.webm)

**Comment by sjyoung428** [comment]
```jsx
const App = () => {
  const { toast } = useToast();
  const onClick = () => {
    toast('Hello World');
  };

  return (
    <>
      <Button onClick={onClick}>버튼</Button>
      <Toaster/>
    </>
  );
};
```
이런 식으로 사용하게 될 듯

**Comment by alstn113** [comment]
저거 아직 사라지지는 않는거죠? 
동영상보니까 없어지지는 않던데

**Comment by sjyoung428** [comment]
아직 그건 안만듬 이제 하려고 ㅋㅋ

**Comment by alstn113** [comment]
컴네 대충 끝내서 이제 작업좀 할게요...

**Comment by sjyoung428** [comment]
원래 context api로 toastlist 관리하려 했는데 잘안되네;;

**Comment by sjyoung428** [comment]
[123123.webm](https://user-images.githubusercontent.com/77968955/204144401-8fe1d248-2b37-445e-a7fe-a7a334a6f9b7.webm)

타임 아웃 default값은 5초

**Comment by sjyoung428** [comment]
[예시](https://user-images.githubusercontent.com/77968955/204248703-c9f8e988-b95a-4a35-98cb-52bcfb466f7f.webm)

useToast훅 사용법
```js
const {toast} = useToast();
toast('hi');
toast('hi','success');
toast('hi','error');
toast.success('hi');
toast.error('hi');
```

**Comment by alstn113** [comment]
framer-motion 으로 애니메이션

**Comment by sjyoung428** [comment]
애니메이션 어떻게 만들지 생각중

**Comment by sjyoung428** [comment]
[toast-animation.webm](https://user-images.githubusercontent.com/77968955/204285167-6a7d03dd-5fb3-4e5c-bba5-e0e83b8d50ed.webm)

**Comment by alstn113** [comment]
저거 애니메이션이 다 같이 작동하는 거 같은데요?
