### ISSUE TITLE
✨ [Feature Request]: upgrade package

### ISSUE THREAD

**Issue by alstn113** [pknu-wap/wap-ui#87]
여기저기 충돌나서 그냥 걍 업그레이드 안함 ㅠㅠ

### 어떤 기능을 제안하시나요? 🤔

- [ ] upgrade dependencies
- [ ] 1. storybook (upgrade dependencies()
- [x] change pakage manager -> 충돌로 인해 X
- [ ] add some libraries

### 이 기능은 어떻게 구현할 수 있을까요? 🛠️

열심히

### 동의 👍

- [X] 다른 이슈가 있는지 확인했습니다. ✅

**Comment by alstn113** [comment]
pnpm으로 바꾸고 build시 tslib 문제가 있어서 @wap-ui/react -> devdependencies에 추가했음

(추가) 이후에 자꾸 storybook babel쪽이랑 에러나는데 뭔가 pkg manager 문제같아서 돌림

**Comment by alstn113** [comment]
elisnt plugin react-hooks 오타 수정

**Comment by neko113** [comment]
> pnpm으로 바꾸고 build시 tslib 문제가 있어서 @wap-ui/react -> devdependencies에 추가했음

이후에 자꾸 storybook babel쪽이랑 에러나는데 뭔가 pkg manager 문제같아서 돌림

**Comment by alstn113** [comment]
upgrade typescript version -> ^5.0.4
storybook에서 satifies를 사용하기 위함.

(추가) ^5.0.4에서 충돌나서 ^4.9.5로 변경

**Comment by alstn113** [comment]
여기저기 버전 바꿀 것도 많고, pnpm + storybook7로 갈려니까 그냥 차라리 새로 만드는게 나을듯
